language: groovy

jdk:
- oraclejdk8

notifications:
  email: false

install:
- ./gradlew -version

script:
- ./gradlew build zipQuickstart --scan --stacktrace
- unzip Quickstart.zip -d quickstart_unzip
- bash -c "cd quickstart_unzip/cpp && ./gradlew clean build"
- bash -c "cd quickstart_unzip/java && ./gradlew clean build"