language: groovy

jdk:
- oraclejdk8

notifications:
  email: false

install:
- ./gradlew -version

script:
- ./gradlew build zipQuickstart --scan --stacktrace
- unzip Quickstart.zip -d quickstart_unzip
- cd quickstart_unzip/cpp
- ./gradlew clean build deploy -Pdeploy-dry
- cd ../java
- ./gradlew clean build deploy -Pdeploy-dry