# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  containers:
  - container: ubuntu18
    image: ubuntu:18.04
  - container: wpilib2018
    image: wpilib/roborio-cross-ubuntu:2018-17.10
  - container: wpilib2019
    image: wpilib/roborio-cross-ubuntu:2019-18.04

pool:
  vmImage: 'Ubuntu 16.04'

container: wpilib2018

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build publishToMavenLocal'
    options: '--scan --stacktrace'
